apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
metadata:
  name: database-env
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==